version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/books_app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL= ${REACT_APP_API_URL}
      - REACT_APP_API_KEY= ${REACT_APP_API_KEY}
    image: app:react
    container_name: react_container
    command: npm start